export const NEW_SECTION = 'NEW_SECTION';
export const ADD_WORK_POSITION = 'ADD_WORK_POSITION';
export const ADD_EDUCATION_POSITION = 'ADD_EDUCATION_POSITION';
export const EDIT_CONTACT_DATA = 'ADD_CONTACT_DATA';
export const EDIT_SKILLS = 'EDIT_SKILLS';
